### PR TITLE
Handle the empty background image

### LINKED ISSUE #66: Exception when configuration doesn't have background image
Here is an image of my gift card configuration

image

Then I go to the index of gift cards and press `PDF`. I am then presented with this exception:

image

### PR DESCRIPTION
**Pull request by Roshyo**
Also make it required
Fixes #66

### CODE REVIEW

File: src/Form/Type/GiftCardConfigurationType.php [hunk 1]
```diff
@@ -43,4 +45,18 @@ public function getBlockPrefix(): string
...
+        $resolver->setDefault('validation_groups', function (FormInterface $form): array {
+            $validationGroups = $this->validationGroups;
+            $data = $form->getData();
+            if (null === $data->getId()) {
+                $validationGroups[] = 'setono_sylius_gift_card_create';
+            }
+
+            return $validationGroups;
+        });
+    }
```
Comment (loevgaard) [inline src/Form/Type/GiftCardConfigurationType.php:61]: I don't understand why this is needed?

Comment (Roshyo) [reply src/Form/Type/GiftCardConfigurationType.php:61]: Oh, it is not anymore. It was on my first attempt. I will remove that

File: src/Resources/config/services/validator.xml [hunk 2]
```diff
@@ -0,0 +1,11 @@
+<?xml version="1.0" encoding="UTF-8" ?>
```
Comment (loevgaard) [inline src/Resources/config/services/validator.xml:1]: Is this file included in the root `services.xml`?

File: src/Resources/config/validation/GiftCardConfiguration.xml [hunk 3]
```diff
@@ -9,6 +9,13 @@
             <option name="fields">code</option>
             <option name="groups">setono_sylius_gift_card</option>
         </constraint>
+        <constraint name="Setono\SyliusGiftCardPlugin\Validator\Constraints\HasBackgroundImage">
+            <option name="groups">
+                <value>setono_sylius_gift_card</value>
+                <value>setono_sylius_gift_card_create</value>
```
Comment (loevgaard) [inline src/Resources/config/validation/GiftCardConfiguration.xml:15]: Why do we need the `setono_sylius_gift_card_create` here?

File: src/Resources/translations/validators.en.yml [hunk 4]
```diff
@@ -15,6 +15,9 @@ setono_sylius_gift_card:
             integer: Amount must be an integer  
             min: Amount cannot be lower than 1
             greater_than_or_equal: The amount must be greater than or equal to 1
+    gift_card_configuration:
+        create:
```
Comment (loevgaard) [inline src/Resources/translations/validators.en.yml:19]: Why this sub namespace?

File: src/Validator/Constraints/HasBackgroundImageValidator.php [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+        if (!$constraint instanceof HasBackgroundImage) {
+            throw new UnexpectedTypeException($constraint, HasBackgroundImage::class);
+        }
+
+        if (!$value instanceof GiftCardConfigurationInterface) {
+            return;
+        }
+
+        $backgroundImage = $value->getBackgroundImage();
+        if (!$backgroundImage instanceof GiftCardConfigurationImageInterface || null === $backgroundImage->getPath()) {
```
Comment (loevgaard) [inline src/Validator/Constraints/HasBackgroundImageValidator.php:26]:
```suggestion
        if (null === $backgroundImage || null === $backgroundImage->getPath()) {
```

File: src/Resources/config/services/validator.xml (hunk 2 above)
Comment (Roshyo) [reply src/Resources/config/services/validator.xml:1]: No it is not, but for some reasons it works fine.
I'm adding it

File: src/Resources/translations/validators.en.yml (hunk 4 above)
Comment (Roshyo) [reply src/Resources/translations/validators.en.yml:19]: Not required anymore

File: src/Resources/config/validation/GiftCardConfiguration.xml (hunk 3 above)
Comment (Roshyo) [reply src/Resources/config/validation/GiftCardConfiguration.xml:15]: We don't anymore

File: src/Validator/Constraints/HasBackgroundImageValidator.php (hunk 5 above)
Comment (Roshyo) [reply src/Validator/Constraints/HasBackgroundImageValidator.php:26]: Is there a specific reason for that ? Or just something like line length ?
I tend to prefer the `instanceof` because it then gives a clear idea of what we expect. (Side effect is autocompletion in IDE as well)
